#!/usr/bin/env python3
"""Exact joint-symmetry and cyclic-space prototype for ``grid-2x4-v1``.

This is intentionally a small, auditable calculation.  It constructs the
fixed-space orbit basis explicitly in the physical (no-padding) Hilbert space,
checks the quotient against the full Hamiltonians, closes the cyclic space
generated by H0 and Hprob, and records endpoint spectral quantities.  It does
not yet claim an adiabatic minimum-gap theorem.
"""

from __future__ import annotations

import hashlib
import itertools
import json
import math
from pathlib import Path
from typing import Any

import numpy as np
import scipy.linalg as la
import scipy.optimize as opt
import scipy.sparse as sp

from instance_registry import load_instance
from spectral_gap_study import build_hamiltonian, _decode_bases
from symmetry_analysis import find_base_automorphisms


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "data" / "accessibility_prototype.json"
INSTANCE_ID = "grid-2x4-v1"
LAM, MU, NU = 5.0, 10.0, 50.0


def single_uniform_driver(n_b: int, k: int) -> sp.csr_matrix:
    """Return sum_r (I-|u><u|)_r on (C^n_b)^tensor-k."""
    u = np.ones(n_b, dtype=float) / math.sqrt(n_b)
    h = sp.csr_matrix(np.eye(n_b) - np.outer(u, u))
    ident = sp.eye(n_b, format="csr")
    dim = n_b**k
    out = sp.csr_matrix((dim, dim), dtype=float)
    for r in range(k):
        term = sp.eye(1, format="csr")
        for s in range(k):
            term = sp.kron(term, h if s == r else ident, format="csr")
        out += term
    return out


def joint_orbits(n_b: int, k: int, base_group: list[tuple[int, ...]]) -> list[list[int]]:
    """Orbits of S_k x G_B on ordered computational tuples."""
    dim = n_b**k
    decoded = _decode_bases(dim, k, n_b)
    powers = np.asarray([n_b**r for r in range(k)], dtype=np.int64)
    assigned = np.zeros(dim, dtype=bool)
    orbits: list[list[int]] = []
    for index in range(dim):
        if assigned[index]:
            continue
        values = tuple(int(x) for x in decoded[index])
        orbit: set[int] = set()
        for permuted in set(itertools.permutations(values)):
            for g in base_group:
                image = np.asarray([g[x] for x in permuted], dtype=np.int64)
                orbit.add(int(image @ powers))
        members = sorted(orbit)
        assigned[members] = True
        orbits.append(members)
    if not assigned.all() or sum(map(len, orbits)) != dim:
        raise AssertionError("joint orbits do not partition the Hilbert space")
    return orbits


def orbit_isometry(orbits: list[list[int]], dim: int) -> sp.csr_matrix:
    rows: list[int] = []
    cols: list[int] = []
    vals: list[float] = []
    for col, orbit in enumerate(orbits):
        amplitude = 1.0 / math.sqrt(len(orbit))
        rows.extend(orbit)
        cols.extend([col] * len(orbit))
        vals.extend([amplitude] * len(orbit))
    return sp.csr_matrix((vals, (rows, cols)), shape=(dim, len(orbits)))


def quotient(H: sp.csr_matrix, S: sp.csr_matrix) -> np.ndarray:
    return np.asarray((S.T @ H @ S).toarray(), dtype=float)


def orthonormal_span(matrix: np.ndarray, relative_tol: float = 1e-11) -> np.ndarray:
    U, singular, _ = np.linalg.svd(matrix, full_matrices=False)
    if singular.size == 0 or singular[0] == 0:
        return np.empty((matrix.shape[0], 0))
    rank = int(np.sum(singular > relative_tol * singular[0]))
    return U[:, :rank]


def cyclic_basis(generators: list[np.ndarray], initial: np.ndarray) -> tuple[np.ndarray, list[int]]:
    """Close the initial vector under a list of Hermitian generators."""
    basis = initial[:, None] / np.linalg.norm(initial)
    dimensions = [1]
    while True:
        candidates = [basis]
        candidates.extend(G @ basis for G in generators)
        enlarged = orthonormal_span(np.column_stack(candidates))
        dimensions.append(enlarged.shape[1])
        if enlarged.shape[1] == basis.shape[1]:
            basis = enlarged
            break
        basis = enlarged
        if basis.shape[1] == basis.shape[0]:
            break
    return basis, dimensions


def cycles(perm: tuple[int, ...]) -> list[int]:
    seen = [False] * len(perm)
    lengths = []
    for start in range(len(perm)):
        if seen[start]:
            continue
        pos, length = start, 0
        while not seen[pos]:
            seen[pos] = True
            pos = perm[pos]
            length += 1
        lengths.append(length)
    return lengths


def symmetric_power_trace(perm: tuple[int, ...], k: int) -> int:
    """Coefficient [z^k] product_l (1-z^l)^(-c_l)."""
    coeff = [0] * (k + 1)
    coeff[0] = 1
    for length in cycles(perm):
        updated = [0] * (k + 1)
        for degree, value in enumerate(coeff):
            if value:
                for repetitions in range((k - degree) // length + 1):
                    updated[degree + repetitions * length] += value
        coeff = updated
    return coeff[k]


def level_summary(values: np.ndarray, matrix_norm: float, residuals: np.ndarray) -> dict[str, Any]:
    """Ground rank and excitation gap using a residual/scale-aware threshold."""
    eps = np.finfo(float).eps
    threshold = float(20 * (2 * residuals.max(initial=0.0) + eps * max(1.0, matrix_norm)))
    g0 = int(np.sum(np.abs(values - values[0]) <= threshold))
    gap = None if g0 == len(values) else float(values[g0] - values[0])
    return {"ground_rank": g0, "excitation_gap": gap, "threshold": threshold}


def eigensystem(H: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    values, vectors = np.linalg.eigh(H)
    residuals = np.linalg.norm(H @ vectors - vectors * values[None, :], axis=0)
    return values, vectors, residuals


def cover_mask(A: np.ndarray, k: int) -> np.ndarray:
    n_b = A.shape[0]
    decoded = _decode_bases(n_b**k, k, n_b)
    distinct = np.asarray([len(set(map(int, row))) == k for row in decoded])
    covered = np.asarray([A[row].any(axis=0).all() for row in decoded])
    return distinct & covered


def analyse() -> dict[str, Any]:
    A, costs, record = load_instance(INSTANCE_ID, require_status="candidate_primary")
    if costs is not None:
        raise AssertionError("prototype expects an unweighted instance")
    n_b, _ = A.shape
    k = int(record["k_star"])
    if n_b & (n_b - 1):
        raise ValueError("prototype currently requires n_B to equal its qubit register dimension")

    Hprob, _ = build_hamiltonian(A, k, LAM, MU, NU)
    H0 = single_uniform_driver(n_b, k)
    dim = n_b**k
    group = find_base_automorphisms(A)
    orbits = joint_orbits(n_b, k, group)
    S = orbit_isometry(orbits, dim)
    gram_error = float(np.linalg.norm((S.T @ S).toarray() - np.eye(S.shape[1]), ord=2))

    H0q, Hpq = quotient(H0, S), quotient(Hprob, S)
    invariance = {
        "H0": float(sp.linalg.norm(H0 @ S - S @ sp.csr_matrix(H0q))),
        "Hprob": float(sp.linalg.norm(Hprob @ S - S @ sp.csr_matrix(Hpq))),
    }

    uniform_full = np.ones(dim) / math.sqrt(dim)
    uniform_q = np.asarray(S.T @ uniform_full).ravel()
    Ku, growth = cyclic_basis([H0q, Hpq], uniform_q)
    cyclic_invariance = {
        "H0": float(np.linalg.norm((np.eye(Ku.shape[0]) - Ku @ Ku.T) @ H0q @ Ku, ord=2)),
        "Hprob": float(np.linalg.norm((np.eye(Ku.shape[0]) - Ku @ Ku.T) @ Hpq @ Ku, ord=2)),
    }

    burnside_dim = sum(symmetric_power_trace(g, k) for g in group) // len(group)
    if burnside_dim != len(orbits):
        raise AssertionError("Burnside dimension disagrees with explicit orbit count")

    mask = cover_mask(A, k)
    P = np.diag(mask.astype(float))
    endpoint: dict[str, Any] = {}
    for label, s in [("s0", 0.0), ("s1", 1.0)]:
        Hfull = ((1 - s) * H0 + s * Hprob).toarray()
        Hsym = (1 - s) * H0q + s * Hpq
        HK = Ku.T @ Hsym @ Ku
        vf, Uf, rf = eigensystem(Hfull)
        vs, Us, rs = eigensystem(Hsym)
        vk, Uk, rk = eigensystem(HK)
        psi_k = np.asarray(S @ (Ku @ Uk[:, 0])).ravel()
        endpoint[label] = {
            "E0_global": float(vf[0]),
            "E0_sym": float(vs[0]),
            "E0_cyclic": float(vk[0]),
            "delta_sym": float(vs[0] - vf[0]),
            "delta_cyclic": float(vk[0] - vs[0]),
            "delta_accessible": float(vk[0] - vf[0]),
            "global": level_summary(vf, float(np.linalg.norm(Hfull, ord=2)), rf),
            "sym": level_summary(vs, float(np.linalg.norm(Hsym, ord=2)), rs),
            "cyclic": level_summary(vk, float(np.linalg.norm(HK, ord=2)), rk),
            "cyclic_ground_cover_probability": float(psi_k @ P @ psi_k),
            "max_residual": {"global": float(rf.max()), "sym": float(rs.max()), "cyclic": float(rk.max())},
        }

    # The orthogonal complement of the joint fixed space contains all
    # nontrivial joint-symmetry sectors.  Because both endpoints commute with
    # the group, this complement is reducing.  Its lowest branch can therefore
    # cross the joint-trivial branch without coupling to it.
    R = la.null_space(S.T.toarray())
    H0_other = R.T @ H0 @ R
    Hp_other = R.T @ Hprob @ R
    other_invariance = {
        "H0": float(np.linalg.norm(np.asarray(S.T @ (H0 @ R)), ord=2)),
        "Hprob": float(np.linalg.norm(np.asarray(S.T @ (Hprob @ R)), ord=2)),
    }

    def e0_sym(s: float) -> float:
        return float(la.eigh((1 - s) * H0q + s * Hpq, subset_by_index=[0, 0], eigvals_only=True)[0])

    def e0_other(s: float) -> float:
        H = (1 - s) * H0_other + s * Hp_other
        return float(la.eigh(H, subset_by_index=[0, 0], eigvals_only=True)[0])

    def branch_difference(s: float) -> float:
        return e0_other(s) - e0_sym(s)

    scan_s = np.linspace(0.0, 1.0, 201)
    differences = np.asarray([branch_difference(float(s)) for s in scan_s])
    brackets = []
    for left, right, f_left, f_right in zip(scan_s[:-1], scan_s[1:], differences[:-1], differences[1:]):
        if f_left == 0 or f_left * f_right < 0:
            brackets.append((float(left), float(right)))
    crossings = []
    for left, right in brackets:
        root = float(opt.brentq(branch_difference, left, right, xtol=1e-13, rtol=1e-13))
        if crossings and abs(root - crossings[-1]["s"]) < 1e-9:
            continue
        energy = e0_sym(root)
        crossings.append({"s": root, "energy": energy, "branch_difference": branch_difference(root)})

    def cyclic_gap(s: float) -> float:
        Hsym = (1 - s) * H0q + s * Hpq
        HK = Ku.T @ Hsym @ Ku
        values = la.eigh(HK, subset_by_index=[0, 1], eigvals_only=True)
        return float(values[1] - values[0])

    coarse_s = np.linspace(0.0, 1.0, 1001)
    coarse_gaps = np.asarray([cyclic_gap(float(s)) for s in coarse_s])
    minimum_index = int(np.argmin(coarse_gaps))
    left = float(coarse_s[max(0, minimum_index - 1)])
    right = float(coarse_s[min(len(coarse_s) - 1, minimum_index + 1)])
    if left == right:
        minimum_s, minimum_gap = left, float(coarse_gaps[minimum_index])
    else:
        minimum = opt.minimize_scalar(cyclic_gap, bounds=(left, right), method="bounded", options={"xatol": 1e-14})
        minimum_s, minimum_gap = float(minimum.x), float(minimum.fun)

    # H0 has off-diagonal coefficient -1/n_B per register, whereas Hprob has
    # +1/(n_B-1).  The linear path therefore cancels all hopping exactly at
    # this rational point.  H is then diagonal and all zero-penalty ordered
    # covers are exactly degenerate.
    cancellation_s = (n_b - 1) / (2 * n_b - 1)
    Hcancel_full = ((1 - cancellation_s) * H0 + cancellation_s * Hprob).toarray()
    Hcancel_sym = (1 - cancellation_s) * H0q + cancellation_s * Hpq
    Hcancel_K = Ku.T @ Hcancel_sym @ Ku
    cancel_values_full = np.linalg.eigvalsh(Hcancel_full)
    cancel_values_sym = np.linalg.eigvalsh(Hcancel_sym)
    cancel_values_K = np.linalg.eigvalsh(Hcancel_K)
    cancel_tol = 1e-10
    cancellation = {
        "s": cancellation_s,
        "off_diagonal_norm_full": float(np.linalg.norm(Hcancel_full - np.diag(np.diag(Hcancel_full)), ord=2)),
        "global_ground_rank": int(np.sum(np.abs(cancel_values_full - cancel_values_full[0]) < cancel_tol)),
        "joint_fixed_ground_rank": int(np.sum(np.abs(cancel_values_sym - cancel_values_sym[0]) < cancel_tol)),
        "cyclic_ground_rank": int(np.sum(np.abs(cancel_values_K - cancel_values_K[0]) < cancel_tol)),
        "cyclic_gap_is_exactly_zero": bool(np.sum(np.abs(cancel_values_K - cancel_values_K[0]) < cancel_tol) > 1),
    }

    derivative = Hprob - H0
    dark_coupling = float(np.linalg.norm(np.asarray(R.T @ (derivative @ S)), ord=2))

    record_path = ROOT / "instances" / "frozen" / f"{INSTANCE_ID}.json"
    return {
        "schema_version": 1,
        "scope": "endpoint prototype; no minimum-path-gap claim",
        "instance_id": INSTANCE_ID,
        "payload_sha256": record["payload_sha256"],
        "frozen_file_sha256": hashlib.sha256(record_path.read_bytes()).hexdigest(),
        "parameters": {"k": k, "lambda": LAM, "mu": MU, "nu": NU},
        "dimensions": {
            "full_valid": dim,
            "symmetric_before_GB": math.comb(n_b + k - 1, k),
            "joint_fixed_orbit_count": len(orbits),
            "joint_fixed_burnside": burnside_dim,
            "cyclic": int(Ku.shape[1]),
        },
        "G_B": {"order": len(group), "permutations_zero_based": [list(g) for g in group]},
        "orbit_sizes": [len(orbit) for orbit in orbits],
        "cyclic_growth": growth,
        "checks": {
            "orbit_isometry_error": gram_error,
            "quotient_invariance_residual": invariance,
            "cyclic_invariance_residual": cyclic_invariance,
            "nontrivial_complement_invariance_residual": other_invariance,
            "dark_derivative_coupling_norm": dark_coupling,
        },
        "endpoint": endpoint,
        "linear_path_diagnostic": {
            "grid_points_crossing_scan": len(scan_s),
            "joint_trivial_vs_nontrivial_crossings": crossings,
            "coarse_plus_local_minimizer_gap": minimum_gap,
            "coarse_plus_local_minimizer_at_s": minimum_s,
            "minimum_cyclic_gap_including_analytic_point": 0.0 if cancellation["cyclic_gap_is_exactly_zero"] else minimum_gap,
            "minimum_cyclic_gap_at_s": cancellation_s if cancellation["cyclic_gap_is_exactly_zero"] else minimum_s,
            "analytic_hopping_cancellation": cancellation,
            "qualification": "numerical diagnostic, not an asymptotic or interval-certified bound",
        },
    }


def main() -> None:
    result = analyse()
    OUTPUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    dims = result["dimensions"]
    print(f"{INSTANCE_ID}: full={dims['full_valid']}, H_sym={dims['joint_fixed_orbit_count']}, K_u={dims['cyclic']}")
    print(f"|G_B|={result['G_B']['order']}; output={OUTPUT.relative_to(ROOT)}")
    print(json.dumps(result["endpoint"], indent=2))
    print(json.dumps(result["linear_path_diagnostic"], indent=2))


if __name__ == "__main__":
    main()
